# Generated by Django 4.0.5 on 2022-06-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('neighborhood', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('expiration_date', models.DateField()),
                ('sale_avaiable', models.BooleanField()),
                ('stock', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_n')),
                ('first_name', models.CharField(max_length=100, verbose_name='first_n')),
                ('dni', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='dni')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('normal', models.BooleanField()),
                ('id_hi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.healthinsurance')),
                ('id_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('amount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.order')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.user'),
        ),
        migrations.AddField(
            model_name='address',
            name='id_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.province'),
        ),
    ]
