# Generated by Django 4.0.5 on 2022-06-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='id_order',
        ),
        migrations.AddField(
            model_name='order',
            name='id_OrderDetail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.orderdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='dni'),
        ),
        migrations.AlterField(
            model_name='user',
            name='normal',
            field=models.BooleanField(verbose_name='disability certificate'),
        ),
    ]
