# Generated by Django 4.0.5 on 2022-06-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_orderdetail_id_order_order_id_orderdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_OrderDetail',
        ),
        migrations.AddField(
            model_name='order',
            name='id_OrderDetail',
            field=models.ManyToManyField(to='data.orderdetail'),
        ),
    ]
