PROVINCE_CHOICES = [
        ('Misiones', 'Provincia de Misiones'),
        ('San Luis', 'Provincia de San Luis'),
        ('San Juan', 'Provincia de San Juan'),
        ('Entre Ríos', 'Provincia de Entre Ríos'),
        ('Santa Cruz', 'Provincia de Santa Cruz'),
        ('Río Negro', 'Provincia de Río Negro'),
        ('Chubut', 'Provincia del Chubut'),
        ('Córdoba', 'Provincia de Córdoba'),
        ('Mendoza', 'Provincia de Mendoza'),
        ('La Rioja', 'Provincia de La Rioja'),
        ('Catamarca', 'Provincia de Catamarca'),
        ('La Pampa', 'Provincia de La Pampa'),
        ('Santiago del Estero', 'Provincia de Santiago del Estero'),
        ('Corrientes', 'Provincia de Corrientes'),
        ('Santa Fe', 'Provincia de Santa Fe'),
        ('Tucumán', 'Provincia de Tucumán'),
        ('Neuquén', 'Provincia del Neuquén'),
        ('Salta', 'Provincia de Salta'),
        ('Chaco', 'Provincia del Chaco'),
        ('Formosa', 'Provincia de Formosa'),
        ('Jujuy', 'Provincia de Jujuy'),
        ('CABA', 'Ciudad Autónoma de Buenos Aires'),
        ('Buenos Aires', 'Provincia de Buenos Aires'),
        ('Tierra del Fuego', 'Provincia de Tierra del Fuego, Antártida e Islas del Atlántico Sur'),
    ]
