# Generated by Django 4.1 on 2022-10-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_alter_certificate_image_binary'),
        ('sale', '0003_saledetail_expiration_date_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.sale'),
        ),
    ]
