# Generated by Django 4.1 on 2022-08-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='persona_id',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='saledetail',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='saledetail',
            old_name='sale_id',
            new_name='sale',
        ),
    ]
