# Generated by Django 4.1 on 2022-09-14 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthinsurance', '0001_initial'),
        ('patient', '0003_alter_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsurance',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='healthinsurance.healthinsurance'),
        ),
    ]
