# Generated by Django 4.1 on 2022-09-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthinsurance', '0001_initial'),
        ('patient', '0004_alter_healthinsurance_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthInsurance',
            new_name='HealthInsurancePatient',
        ),
    ]
