# Generated by Django 4.1 on 2022-09-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_healthinsurancepatient_healthinsurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='province',
            field=models.CharField(default='default', max_length=25),
            preserve_default=False,
        ),
    ]
