# Generated by Django 4.1 on 2022-10-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_remove_certificate_image_remove_certificate_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image_binary',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
