# Generated by Django 4.1 on 2022-11-17 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthinsurance', '0001_initial'),
        ('patient', '0013_alter_patient_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsurancepatient',
            name='healthinsurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='obrasocial_name', to='healthinsurance.healthinsurance'),
        ),
        migrations.AlterField(
            model_name='healthinsurancepatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='patient.patient'),
        ),
    ]
