# Generated by Django 4.1 on 2022-08-24 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='person',
            name='employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
