# Generated by Django 4.1 on 2022-09-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_certificate_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsurance',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_insurance', to='users.person'),
        ),
    ]
