# Generated by Django 4.1 on 2022-10-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(default='https://google.com', max_length=256),
            preserve_default=False,
        ),
    ]
