# Generated by Django 4.1 on 2022-10-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='market',
            field=models.CharField(choices=[('Y', 'Disponible en Market'), ('N', 'No disponible en Market')], default='N', max_length=23),
        ),
    ]
