# Generated by Django 4.1 on 2022-10-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='market',
            field=models.CharField(choices=[('Y', 'Permitido en Market'), ('N', 'No permitido en Market')], default='N', max_length=23),
        ),
    ]
