# Generated by Django 4.1 on 2022-10-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='expiration_date',
            field=models.DateField(default='2022-10-07'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=9),
        ),
    ]
