# Generated by Django 4.1 on 2022-10-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_remove_saledetail_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aceptado'), ('C', 'Cancelado')], default='P', max_length=9),
        ),
    ]
