# Generated by Django 4.1 on 2022-10-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
