# Generated by Django 4.1 on 2022-10-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_alter_saledetail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateField(auto_created=True, default='2022-10-1'),
            preserve_default=False,
        ),
    ]
