# Generated by Django 4.1 on 2022-08-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_person_id_healthinsurance_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.person'),
        ),
    ]
