# Generated by Django 4.1 on 2022-09-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_rename_healthinsurance_healthinsurancepatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
