# Generated by Django 4.1 on 2022-09-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthinsurance', '0001_initial'),
        ('patient', '0007_remove_healthinsurancepatient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsurancepatient',
            name='healthinsurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='healthinsurance.healthinsurance'),
        ),
    ]
