# Generated by Django 4.1 on 2022-09-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_patient_city_patient_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlobCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.TextField(db_column='data', default=' ')),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(upload_to='patients/certificates'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='image_blob',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.blobcertificate'),
            preserve_default=False,
        ),
    ]
