# Generated by Django 4.1 on 2022-09-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_blobcertificate_alter_certificate_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='image_blob',
        ),
        migrations.AddField(
            model_name='blobcertificate',
            name='certificate',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.certificate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blobcertificate',
            name='blob',
            field=models.TextField(db_column='data'),
        ),
    ]
