# Generated by Django 4.1 on 2022-09-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_remove_certificate_image_blob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blobcertificate',
            name='blob',
            field=models.TextField(db_column='data', default=' '),
        ),
    ]
