# Generated by Django 4.1 on 2022-09-30 11:16

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_blobcertificate_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='blobcertificate',
            name='image',
            field=models.ImageField(default='patients/certificates/default_certificate.jpg', upload_to=patient.models.BlobCertificate.set_data),
        ),
        migrations.AlterField(
            model_name='blobcertificate',
            name='blob',
            field=models.TextField(blank=True, db_column='data', default=' '),
        ),
    ]
