# Generated by Django 4.1 on 2022-10-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_patient_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='province',
            field=models.CharField(max_length=25),
        ),
    ]
